#!/bin/bash
script_pwd=$(cd "$(dirname "$0")"; pwd)
export $(cat $script_pwd/.env | xargs)
last_commit=$(git -C $REPO_DIR rev-parse --short HEAD)
echo $last_commit
git -C $REPO_DIR checkout $BRANCH && git -C $REPO_DIR pull -f || git clone $REPO $REPO_DIR -b $BRANCH
echo $(git -C $REPO_DIR rev-parse --short HEAD)
# Стягиваем лэндинг
cd $script_pwd/..
git reset --hard
git pull -f
npm i
# Если обновилось запускаем скрипт
if [ "$last_commit" != $(git -C $REPO_DIR rev-parse --short HEAD) ]; then
    mkdir -p $script_pwd/../docs/nodes
    node $script_pwd/ci.js $REPO_DIR $script_pwd/../docs

    mkdir -p $script_pwd/../i18n/ru/docusaurus-plugin-content-docs/current/nodes
    mkdir -p $script_pwd/../i18n/en/docusaurus-plugin-content-docs/current/nodes

    node $script_pwd/ci.js $REPO_DIR $script_pwd/../i18n/ru/docusaurus-plugin-content-docs/current
    npx docusaurus write-translations --locale ru
    node $script_pwd/translateSections.js $script_pwd/../i18n/ru/docusaurus-plugin-content-docs/current.json $REPO_DIR/src/locales/ru.json
    node $script_pwd/ci.js $REPO_DIR $script_pwd/../i18n/en/docusaurus-plugin-content-docs/current
    npx docusaurus write-translations --locale en
    node $script_pwd/translateSections.js $script_pwd/../i18n/en/docusaurus-plugin-content-docs/current.json $REPO_DIR/src/locales/en.json

    git add docs i18n
    git commit -m "Automatically generated by CI"
    git push
fi
npm run build
